DROP TABLE TACHEUTILISATEUR;
DROP TABLE DEPENDANCETACHE;
DROP TABLE PERIODICITE;
DROP VIEW TACHES;
DROP TABLE TACHEFINI;
DROP TABLE TACHENCOURS;
DROP TABLE SCORE;
DROP TABLE LISTETACHE;
DROP TABLE PROJET;
DROP TABLE UTILISATEUR;

